spring:
  datasource:
    initialize: true
    
  h2:
    console: 
      path: /console
      enabled: true

  multi-datasource:
    basePackages: com.hanuritien.integalcoordinate.geofencedata.multijpa.coordinate
    default-datasource-name: coordinates
    datasources:
      coordinates:
        url: jdbc:h2:~/db1;AUTO_SERVER=TRUE;DB_CLOSE_ON_EXIT=FALSE
        username: sa
        password: 
        

logging:
  level:
    org.springframework:
      boot: DEBUG
      transaction: DEBUG
    org.sbcoba.springboot.multidatasource: DEBUG