server:
  port: 8080
  
debug: true
  
spring:
  datasource:
    initialize: false
    
    
  h2:
    console: 
      path: /console
      enabled: true

 # multi-datasource:
 #   basePackages: com.hanuritien.integalcoordinate.geofencedata.multijpa
 #   default-datasource-name: coordinates
 #   datasources:
 #     coordinates:
 #       url: jdbc:h2:~/hanuritien/coordinate;AUTO_SERVER=TRUE;CACHE_SIZE=8192;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
 #       validationQuery: select 1    
 #     inout:
 #       url: jdbc:h2:~/hanuritien/inout;AUTO_SERVER=TRUE;CACHE_SIZE=8192;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
 #       validationQuery: select 1

  jpa:
    generate-ddl: true
    show-sql: true
    

logging:
  level:
    org.springframework:
      boot: DEBUG
      transaction: DEBUG
    com.hanuritien.integalcoordinate: DEBUG
        
datasource:
    inout:
        url: jdbc:h2:~/hanuritien/inout;AUTO_SERVER=TRUE;CACHE_SIZE=8192;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
        user: sa
        pass:
        driverClassName: org.h2.Driver
        database-platform: org.hibernate.dialect.H2Dialect
        show_sql: true
        hbm2ddl: none
    coordinate:
        url: jdbc:h2:~/hanuritien/coordinate;AUTO_SERVER=TRUE;CACHE_SIZE=8192;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
        user: sa
        pass:
        driverClassName: org.h2.Driver
        database-platform: org.hibernate.dialect.H2Dialect
        show_sql: true
        hbm2ddl: none 
