server:
  port: 8081
  
debug: true

spring:
  datasource:
    initialize: true
#    url: jdbc:mysql://192.168.0.90:13306/BIO_LMS
#    username: bio_lms
#    password: dpfdpadptmtlstp!@#
#    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:h2:~/hanuritien/inout;AUTO_SERVER=TRUE;CACHE_SIZE=8192;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    driverClassName: org.h2.Driver  
    

  jpa:
    generate-ddl: false
    show-sql: false  
    database-platform: org.hibernate.dialect.H2Dialect 
    hibernate:
      ddl-auto: validate
    

logging:
  level:
    org.springframework:
      boot: DEBUG
      transaction: DEBUG
    com.hanuritien.integalcoordinate: DEBUG
    org.hibernate.SQL: WARN

     